### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by sreenik250** [keosariel/supabase-client#2]
async def Upd(): 
    error, result = await (
        cl.table("countries")
        .update(
            { 'name': 'Muscat' } ,
            { 'name': 'Jersey' }
        )                   
    )

asyncio.run(Upd())

Tried to update Jersey with Muscat in the above countries table.  Got the below error:

Traceback (most recent call last):
  File "c:\Citrus\PY\SupabaseTest.py", line 39, in <module>
    asyncio.run(Upd())
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "c:\Citrus\PY\SupabaseTest.py", line 31, in Upd
    error, result = await (
  File "C:\Python310\lib\site-packages\supabase_client\_supabase_clients.py", line 88, in update
    return self._error(response, json_data), json_data
  File "C:\Python310\lib\site-packages\supabase_client\_supabase_clients.py", line 182, in _error
    raise error
supabase_client.supebase_exceptions.SupabaseError: {'code': 'PGRST104', 'details': 'Failed to parse [("name","Muscat")]', 'hint': None, 'message': 'Unexpected param or filter missing operator'}
PS C:\PgDCP>

**Comment by keosariel** [comment]
ohh sorry about this, noticed this issue too late. Would update the lib right away!
