### ISSUE TITLE
delete error

### ISSUE THREAD

**Issue by PaulExplorer** [keosariel/supabase-client#6]
`async def requests():
   await supabase.table("test").delete({"name":"test"})
    
asyncio.run(requests())`

Traceback (most recent call last):
  File "test.py", line 20, in <module>
    asyncio.run(requests())
  File "Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "test.py", line 10, in requests
    await supabase.table("test").delete({"name":"test"})
  File "Lib\site-packages\supabase_client\_supabase_clients.py", line 149, in delete
    return self._error(response, json_data), json_data
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Lib\site-packages\supabase_client\_supabase_clients.py", line 182, in _error
    raise error
supabase_client.supebase_exceptions.SupabaseError: None`

@keosariel pls help my level in english is null

**Comment by keosariel** [comment]
Hi @PLLX76,

Sorry for the inconvenience and I'd recommend you use a more actively maintained repo by the Supabase team [here](https://github.com/supabase-community/supabase-py)
